name = "woke-notion-worker"
main = "./index.ts"
compatibility_date = "2024-04-19"
route = { pattern = "api.woke.net/streamers/*", zone_name = "woke.net" }

[vars]
INDEX_DB = "243b9b9e-0a3a-4460-b9a4-3abccf27126f"
TTL = 30
